export const baseSalary = 1614.69;

const groupToQuantifirerMap = {
  20:	5.588,
  19:	4.897,
  18: 3.587,
  17: 3.192,
  16: 2.811,
  15: 2.509,
  14: 2.311,
  13: 2.198,
  12: 2.144,
  11: 2.074,
  10: 2.020,
  9: 1.961,
  8: 1.950,
  7: 1.926,
  6: 1.906,
  5: 1.896,
  4: 1.876,
  3: 1.813,
  2: 1.749,
  1: 1.577,
};

const occupationsToGroupMap = [
  {
    hub: 'Komenda Główna',
    map: [
      { name: 'Komendant Główny PSP', group: 20 },
      { name: 'Zastępca Komendanta Głównego PSP', group: 19 },
      { name: 'Dyrektor biura', group: 17 },
      { name: 'Doradca Komendanta', group: 16 },
      { name: 'Główny księgowy', group: 16 },
      { name: 'Zastępca dyrektora biura', group: 16 },
      { name: 'Główny specjalista', group: 15 },
      { name: 'Naczelnik wydziału', group: 15 },
      { name: 'Specjalista dziedzinowy', group: 15 },
      { name: 'Radca prawny ', group: 15 },
      { name: 'Kapelan krajowy', group: 14 },
      { name: 'Dyżurny operacyjny kraju', group: 13 },
      { name: 'Kierownik sekcji', group: 13 },
      { name: 'Zastępca naczelnika wydziału', group: 13 },
      { name: 'Starszy specjalista', group: 12 },
      { name: 'Zastępca dyżurnego operacyjnego kraju', group: 12 },
      { name: 'Pomocnik dyżurnego operacyjnego kraju', group: 10 },
      { name: 'Specjalista', group: 10 },
      { name: 'Starszy inspektor sztabowy', group: 9 },
      { name: 'Starszy inspektor', group: 8 },
      { name: 'Inspektor', group: 7 },
      { name: 'Starszy operator sprzętu', group: 7 },
      { name: 'Starszy technik sztabowy', group: 7 },
      { name: 'Starszy ratownik-kierowca', group: 5 },
      { name: 'Starszy technik', group: 5 },
      { name: 'Ratownik-kierowca', group: 4 },
      { name: 'Technik', group: 4 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
      { name: 'Młodszy technik', group: 2 },
      { name: 'Stażysta', group: 1 },
    ],
  },
  {
    hub: 'Komendy Wojewódzkie PSP z wyłączeniem Ośrodków Szkolenia',
    map: [
      { name: 'Komendant wojewódzki PSP', group: 18 },
      { name: 'Zastępca komendanta wojewódzkiego PSP', group: 17 },
      { name: 'Główny księgowy', group: 14 },
      { name: 'Naczelnik wydziału ', group: 14 },
      { name: 'Główny specjalista ', group: 13 },
      { name: 'Specjalista dziedzinowy', group: 13 },
      { name: 'Radca prawny', group: 13 },
      { name: 'Zastępca naczelnika wydziału (w KW I kat.)', group: 13 },
      { name: 'Kierownik sekcji', group: 12 },
      { name: 'Zastępca naczelnika wydziału (w KW II kat.)', group: 12 },
      { name: 'Dyżurny operacyjny (w KW I kat.)', group: 11 },
      { name: 'Oficer operacyjny', group: 11 },
      { name: 'Starszy specjalista', group: 11 },
      { name: 'Dyżurny operacyjny (w KW II kat.)', group: 10 },
      { name: 'Kapelan wojewódzki', group: 10 },
      { name: 'Specjalista ', group:9  },
      { name: 'Starszy inspektor sztabowy', group: 9 },
      { name: 'Zastępca dyżurnego operacyjnego', group: 9 },
      { name: 'Młodszy specjalista', group: 8 },
      { name: 'Pomocnik dyżurnego operacyjnego', group: 7 },
      { name: 'Starszy inspektor', group: 7 },
      { name: 'Starszy technik sztabowy', group: 7 },
      { name: 'Inspektor', group: 6 },
      { name: 'Starszy ratownik-kierowca', group: 4 },
      { name: 'Starszy technik', group: 4 },
      { name: 'Ratownik-kierowca', group: 3 },
      { name: 'Technik', group: 3 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
      { name: 'Młodszy technik', group: 2 },
      { name: 'Stażysta', group: 1 },
    ],
  },
  {
    hub: 'Komendy Powiatowe i Miejskie PSP',
    map: [
      { name: 'Komendant powiatowy (miejski) PSP (w KP I kat.)', group: 17 },
      { name: 'Komendant powiatowy (miejski) PSP (w KP II kat.)', group: 16 },
      { name: 'Zastępca komendanta powiatowego (miejskiego) PSP (w KP I kat.)', group: 16 },
      { name: 'Komendant powiatowy (miejski) PSP (w KP III, IV i V kat.)', group: 15 },
      { name: 'Zastępca komendanta powiatowego (miejskiego) PSP (w KP II kat.)', group: 15 },
      { name: 'Zastępca komendanta powiatowego (miejskiego) PSP (w KP III, IV i V kat.)', group: 14 },
      { name: 'Dowódca jednostki ratowniczo-gaśniczej', group: 13 },
      { name: 'Główny księgowy (w KP I kat.)', group: 13 },
      { name: 'Naczelnik wydziału (w KP I kat.)', group: 13 },
      { name: 'Naczelnik wydziału właściwy do spraw operacyjnych (w KP II kat.)', group: 13 },
      { name: 'Główny księgowy (w KP II kat.)', group: 12 },
      { name: 'Naczelnik wydziału (w KP II kat.)', group: 12 },
      { name: 'Naczelnik wydziału właściwy do spraw operacyjnych (w KP III, IV i V kat.)', group: 12 },
      { name: 'Zastępca dowódcy jednostki ratowniczo-gaśniczej', group: 12 },
      { name: 'Zastępca naczelnika wydziału (w KP I kat.)', group: 12 },
      { name: 'Starszy specjalista właściwy ds. ochrony danych (w KP I kat.)', group: 12 },
      { name: 'Główny księgowy (w KP III, IV i V kat.)', group: 11 },
      { name: 'Naczelnik wydziału (w KP III, IV i V kat.)', group: 11 },
      { name: 'Zastępca naczelnika wydziału (w KP II kat.)', group: 11 },
      { name: 'Kierownik sekcji (w KP I i II kat.)', group: 11 },
      { name: 'Dowódca zmiany', group: 10 },
      { name: 'Dyżurny operacyjny (w KP I i II kat.)', group: 10 },
      { name: 'Kierownik sekcji (w KP III, IV i V kat.) ', group: 10 },
      { name: 'Oficer operacyjny (w KP I i II kat.)', group: 10 },
      { name: 'Starszy specjalista', group: 10 },
      { name: 'Zastępca naczelnika wydziału (w KP III, IV i V kat.)', group: 10 },
      { name: 'Dyżurny operacyjny (w KP III, IV i V kat.)', group: 9 },
      { name: 'Specjalista', group: 9 },
      { name: 'Starszy dyżurny stanowiska kierowania', group: 9 },
      { name: 'Starszy inspektor sztabowy', group: 9 },
      { name: 'Starszy ratownik specjalista', group: 9 },
      { name: 'Zastępca dowódcy zmiany', group: 9 },
      { name: 'Zastępca dyżurnego operacyjnego (w KP I i II kat.)', group: 9 },
      { name: 'Dowódca sekcji', group: 8 },
      { name: 'Młodszy specjalista', group: 8 },
      { name: 'Absolwent-oficer', group: 7 },
      { name: 'Dowódca zastępu', group: 7 },
      { name: 'Ratownik specjalista', group: 7 },
      { name: 'Starszy inspektor', group: 7 },
      { name: 'Starszy operator sprzętu', group: 7 },
      { name: 'Starszy technik sztabowy', group: 7 },
      { name: 'Dyżurny stanowiska kierowania', group: 6 },
      { name: 'Inspektor', group: 6 },
      { name: 'Operator sprzętu', group: 6 },
      { name: 'Specjalista dziedzinowy', group: 6 },
      { name: 'Młodszy inspektor', group: 5 },
      { name: 'Młodszy operator sprzętu', group: 5 },
      { name: 'Młodszy ratownik specjalista', group: 5 },
      { name: 'Absolwent-aspirant', group: 4 },
      { name: 'Starszy ratownik', group: 4 },
      { name: 'Starszy ratownik-kierowca', group: 4 },
      { name: 'Starszy technik', group: 4 },
      { name: 'Starszy ratownik medyczny służby', group: 4 },
      { name: 'Ratownik', group: 3 },
      { name: 'Ratownik-kierowca', group: 3 },
      { name: 'Ratownik medyczny służby', group: 3 },
      { name: 'Technik', group: 3 },
      { name: 'Młodszy ratownik', group: 2 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
      { name: 'Młodszy technik', group: 2 },
      { name: 'Stażysta', group: 1 },
    ],
  },
  {
    hub: 'Szkoła Główna Służby Pożarniczej',
    map: [
      { name: 'Komendant', group: 19 },
      { name: 'Zastępca Komendanta', group: 18 },
      { name: 'Kanclerz', group: 17 },
      { name: 'Profesor', group: 16 },
      { name: 'Dyrektor', group: 15 },
      { name: 'Profesor uczelni', group: 15 },
      { name: 'Dowódca pododdziałów szkolnych', group: 14 },
      { name: 'Kierownik działu', group: 14 },
      { name: 'Adiunkt', group: 13 },
      { name: 'Dowódca jednostki ratowniczo-gaśniczej', group: 13 },
      { name: 'Główny specjalista', group: 13 },
      { name: 'Dowódca kompanii szkolnej', group: 12 },
      { name: 'Oficer dyżurny', group: 12 },
      { name: 'Starszy wykładowca', group: 12 },
      { name: 'Zastępca dowódcy jednostki ratowniczo-gaśniczej', group: 12 },
      { name: 'Specjalista dziedzinowy', group: 12 },
      { name: 'Wykładowca', group: 11 },
      { name: 'Zastępca dowódcy kompanii szkolnej', group: 11 },
      { name: 'Asystent', group: 10 },
      { name: 'Dowódca zmiany', group: 10 },
      { name: 'Kierownik referatu', group: 10 },
      { name: 'Starszy ratownik specjalista', group: 10 },
      { name: 'Starszy specjalista', group: 10 },
      { name: 'Lektor', group: 9 },
      { name: 'Specjalista', group: 9 },
      { name: 'Starszy instruktor', group: 9 },
      { name: 'Zastępca dowódcy zmiany', group: 9 },
      { name: 'Dowódca sekcji', group: 8 },
      { name: 'Instruktor', group: 8 },
      { name: 'Młodszy specjalista', group: 8 },
      { name: 'Starszy inspektor sztabowy', group: 8 },
      { name: 'Absolwent-oficer', group: 7 },
      { name: 'Dowódca zastępu', group: 7 },
      { name: 'Ratownik specjalista', group: 7 },
      { name: 'Starszy dyżurny szkolnego stanowiska kierowania', group: 7 },
      { name: 'Starszy inspektor', group: 7 },
      { name: 'Starszy operator sprzętu', group: 7 },
      { name: 'Inspektor', group: 6 },
      { name: 'Operator sprzętu', group: 6 },
      { name: 'Młodszy inspektor', group: 5 },
      { name: 'Młodszy instruktor', group: 5 },
      { name: 'Młodszy operator sprzętu', group: 5 },
      { name: 'Młodszy ratownik specjalista', group: 5 },
      { name: 'Absolwent-aspirant', group: 4 },
      { name: 'Dyżurny szkolnego stanowiska kierowania', group: 4 },
      { name: 'Starszy ratownik', group: 4 },
      { name: 'Starszy ratownik medyczny służby', group: 4 },
      { name: 'Starszy ratownik-kierowca', group: 4 },
      { name: 'Starszy technik', group: 4 },
      { name: 'Ratownik', group: 3 },
      { name: 'Ratownik medyczny służby', group: 3 },
      { name: 'Ratownik-kierowca', group: 3 },
      { name: 'Technik', group: 3 },
      { name: 'Młodszy ratownik', group: 2 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
      { name: 'Młodszy technik', group: 2 },
      { name: 'Stażysta', group: 1 },
    ],
  },
  {
    hub: 'Pozostałe Szkoły, Ośrodki Szkolenia KW, Instytuty Badawcze oraz Centralne Muzeum Pożarnictwa',
    map: [
      { name: 'Dyrektor (w Instytucie Badawczym)', group: 18 },
      { name: 'Dyrektor (w Centralnym Muzeum Pożarnictwa)', group: 16 },
      { name: 'Komendant', group: 17 },
      { name: 'Zastępca dyrektora', group: 16 },
      { name: 'Zastępca komendanta', group: 16 },
      { name: 'Kierownik zakładu', group: 14 },
      { name: 'Naczelnik wydziału właściwy do spraw kształcenia', group: 14 },
      { name: 'Naczelnik ośrodka szkolenia', group: 14 },
      { name: 'Główny księgowy', group: 13 },
      { name: 'Główny specjalista', group: 13 },
      { name: 'Naczelnik wydziału', group: 13 },
      { name: 'Dowódca jednostki ratowniczo-gaśniczej', group: 13 },
      { name: 'Adiunkt', group: 12 },
      { name: 'Dowódca kompanii szkolnej', group: 12 },
      { name: 'Kierownik laboratorium', group: 12 },
      { name: 'Kierownik sekcji', group: 12 },
      { name: 'Kierownik zespołu przedmiotowego', group: 12 },
      { name: 'Oficer dyżurny', group: 12 },
      { name: 'Starszy wykładowca', group: 12 },
      { name: 'Specjalista dziedzinowy', group: 12 },
      { name: 'Zastępca dowódcy jednostki ratowniczo-gaśniczej', group: 12 },
      { name: 'Zastępca naczelnika ośrodka szkolenia', group: 12 },
      { name: 'Zastępca naczelnika wydziału', group: 12 },
      { name: 'Wykładowca', group: 11 },
      { name: 'Zastępca dowódcy kompanii szkolnej', group: 11 },
      { name: 'Dowódca zmiany', group: 10 },
      { name: 'Starszy specjalista', group: 10 },
      { name: 'Specjalista', group: 9 },
      { name: 'Starszy instruktor', group: 9 },
      { name: 'Starszy ratownik specjalista', group: 9 },
      { name: 'Zastępca dowódcy zmiany', group: 9 },
      { name: 'Dowódca sekcji', group: 8 },
      { name: 'Instruktor', group: 8 },
      { name: 'Młodszy specjalista', group: 8 },
      { name: 'Młodszy wykładowca', group: 8 },
      { name: 'Starszy inspektor sztabowy', group: 8 },
      { name: 'Absolwent-oficer', group: 7 },
      { name: 'Dowódca zastępu', group: 7 },
      { name: 'Ratownik specjalista', group: 7 },
      { name: 'Starszy dyżurny szkolnego stanowiska kierowania', group: 7 },
      { name: 'Starszy inspektor', group: 7 },
      { name: 'Starszy operator sprzętu', group: 7 },
      { name: 'Starszy technik sztabowy', group: 7 },
      { name: 'Inspektor', group: 6 },
      { name: 'Operator sprzętu', group: 6 },
      { name: 'Młodszy inspektor', group: 5 },
      { name: 'Młodszy instruktor', group: 5 },
      { name: 'Młodszy ratownik specjalista', group: 5 },
      { name: 'Absolwent-aspirant', group: 4 },
      { name: 'Dyżurny szkolnego stanowiska kierowania', group: 4 },
      { name: 'Starszy ratownik', group: 4 },
      { name: 'Starszy ratownik-kierowca', group: 4 },
      { name: 'Starszy ratownik medyczny służby', group: 4 },
      { name: 'Starszy technik', group: 4 },
      { name: 'Ratownik', group: 3 },
      { name: 'Ratownik-kierowca', group: 3 },
      { name: 'Ratownik medyczny służby', group: 3 },
      { name: 'Technik', group: 3 },
      { name: 'Młodszy ratownik', group: 2 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
      { name: 'Młodszy technik', group: 2 },
      { name: 'Stażysta', group: 1 },
    ],
  },
  {
    hub: 'Inspektorat Wojskowej Straży Pożarnej',
    map: [
      { name: 'Główny specjalista', group: 15 },
      { name: 'Starszy specjalista', group: 13 },
      { name: 'Specjalista', group: 11 },
      { name: 'Młodszy specjalista', group: 9 },
    ],
  },
  {
    hub: 'Delegatura Wojskowej Straży Pożarnej',
    map: [
      { name: 'Główny specjalista', group: 13 },
      { name: 'Starszy specjalista', group: 11 },
      { name: 'Specjalista', group: 10 },
      { name: 'Młodszy specjalista', group: 8 },
    ],
  },
  {
    hub: 'Wojskowe Straże Pożarne',
    map: [
      { name: 'Dowódca wojskowej straży pożarnej', group: 10 },
      { name: 'Dowódca zastępu', group: 7 },
      { name: 'Starszy ratownik-kierowca', group: 4 },
      { name: 'Ratownik', group: 3 },
      { name: 'Ratownik-kierowca', group: 3 },
      { name: 'Technik', group: 3 },
      { name: 'Młodszy ratownik', group: 2 },
      { name: 'Młodszy ratownik-kierowca', group: 2 },
    ],
  },
];

export const occupationsMap = occupationsToGroupMap.map(hubData => ({
  hub: hubData.hub,
  map: hubData.map.map(occupation => ({
    ...occupation,
    quantifier: groupToQuantifirerMap[occupation.group],
  }))
}));

export const rankMap = [
  { name: 'Generał brygadier', value: 1772 },
  { name: 'Nadbrygadier', value: 1622 },
  { name: 'Starszy brygadier', value: 1472 },
  { name: 'Brygadier', value: 1452 },
  { name: 'Młodszy brygadier', value: 1432 },
  { name: 'Starszy kapitan', value: 1412 },
  { name: 'Kapitan', value: 1392 },
  { name: 'Młodszy kapitan', value: 1372 },
  { name: 'Aspirant sztabowy', value: 1317 },
  { name: 'Starszy aspirant', value: 1297 },
  { name: 'Aspirant', value: 1277 },
  { name: 'Młodszy aspirant', value: 1257 },
  { name: 'Starszy ogniomistrz', value: 1202 },
  { name: 'Ogniomistrz', value: 1182 },
  { name: 'Młodszy ogniomistrz', value: 1162 },
  { name: 'Starszy sekcyjny', value: 1142 },
  { name: 'Sekcyjny', value: 1122 },
  { name: 'Starszy strażak', value: 1082 },
  { name: 'Strażak', value: 1072 },
];

export interface SalaryFormData {
  hub: string;
  occupation: string;
  rank: string;
  serviceAllowance: number;
  dutyStart: string;
}
